# Generated by Django 3.0.5 on 2021-07-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20210716_0003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="count",
        ),
    ]
