# Generated by Django 3.0.5 on 2021-07-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210721_0942"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscribe",
            name="unique_follow",
        ),
    ]
